error-demonlist-malformedvideourl = Hatalı video URL'si
error-demonlist-bannedfromsubmissions = Listten yasaklısınız!
error-demonlist-claimunverified = Bu oyuncuya talebiniz daha doğrulanmış değil!
error-demonlist-vpsdetected = VPS kullanımı algılandı! VPN'iniz açıksa lütfen kapatın.
error-demonlist-nothirdpartysubmissions = Bu oyuncu sadece kendisinin kayıt atabilmesini talep etmiştir.
error-demonlist-submitternotfound = ID'si { $id } olan ibraz eden bulunamadı.
error-demonlist-notenotfound = ID'si { $note-id } olan not ID'si { $record-id } olan kayıtda bulunamadı.
error-demonlist-creatornotfound = ID'si { $player-id } olan oyuncu ID'si { demon-id } olan demonun creator(lar)ından değildir.
error-demonlist-nationalitynotfound = ISO kodu { $iso-code } olan ülke bulunamadı.
error-demonlist-subdivisionnotfound = No subdivision with code { $subdivision-code } found in nation { $nation-code }
error-demonlist-playernotfound = No player with id { $player-id } found
error-demonlist-playernotfoundname = No player with name { $player-name } found
error-demonlist-demonnotfound = No demon with id { $demon-id } found
error-demonlist-demonnotfoundname = No demon with name { $demon-name } found
error-demonlist-demonnotfoundposition = No demon at position { $demon-position } found
error-demonlist-recordnotfound = No record with id { $record-id } found
error-demonlist-claimnotfound = No claim by user { $member-id } on player { $player-id } found
error-demonlist-creatorexists = This player is already registered as a creator on this demon
error-demonlist-duplicatevideo = This video is already used by record #{ $record-id }
error-demonlist-nonationset = Attempt to set subdivision without nation
error-demonlist-conflictingclaims = The players '{ $player-1 }' and '{ $player-2 }' have verified claims by different pointercrate users
error-demonlist-invalidrequirement = Record requirement needs to be greater than -1 and smaller than 101
error-demonlist-invalidposition = Demon position needs to be greater than or equal to 1 and smaller than or equal to { $maximal }
error-demonlist-invalidprogress = Record progress must lie between { $requirement } and 100%!
error-demonlist-submissionexists = This record is already { $record-status } (existing record: { $record-id })
error-demonlist-playerbanned = The given player is banned and thus cannot have non-rejected records on the list!
error-demonlist-submitlegacy = Legacy demonları için kayıt gönderemezsiniz
error-demonlist-non100extended = Only 100% records can be submitted for the extended section of the list
error-demonlist-unsupportedvideohost = The given video host is not supported. Supported are 'youtube', 'vimeo', 'everyplay', 'twitch' and 'bilibili'
error-demonlist-demonnamenotunique = There are multiple demons with the given name
error-demonlist-noteempty = Notes mustn't be empty!
error-demonlist-alreadyclaimed = This player already has a verified claim associated with them
error-demonlist-rawrequired = Raw footage much be provided to submit this record
error-demonlist-malformedrawurl = Raw footage needs to be a valid URL
error-demonlist-invalidlevelid = Level ID needs to be positive

error-demonlist-ratelimit-record-submit = You're submitting too many records too fast!
error-demonlist-ratelimit-record-submit-global = Too many records are being submitted right now!
error-demonlist-ratelimit-new-submitters = DDoS protection ratelimit
error-demonlist-ratelimit-geolocate = You can only geolocate once per month!
error-demonlist-ratelimit-add-demon = Please don't spam the button, rSteel